### ISSUE TITLE
Crashed on the xposed installed phone

### ISSUE THREAD

**Issue by openproject** [asLody/whale#10]
02-25 23:43:30.471 E/easybike_easybike(10313): java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/com.jingyao.easybike-2/lib/arm/libwhale.so"
02-25 23:43:30.471 E/easybike_easybike(10313): 	at java.lang.Runtime.loadLibrary0(Runtime.java:977)
02-25 23:43:30.471 E/easybike_easybike(10313): 	at java.lang.System.loadLibrary(System.java:1530)
02-25 23:43:30.471 E/easybike_easybike(10313): 	at com.lody.whale.WhaleRuntime.<clinit>(WhaleRuntime.java:19)
02-25 23:43:30.471 E/easybike_easybike(10313): 	at com.lody.whale.WhaleRuntime.hookMethodNative(Native Method)
02-25 23:43:30.471 E/easybike_easybike(10313): 	at com.lody.whale.xposed.XposedBridge.hookMethod(XposedBridge.java:100)
02-25 23:43:30.471 E/easybike_easybike(10313): 	at com.lody.whale.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:187)
02-25 23:43:30.471 E/easybike_easybike(10313): 	at com.jingyao.easybike.tools.upi.Hooks.init(Hooks.kt:34)
02-25 23:43:30.471 E/easybike_easybike(10313): 	at com.hellobike.atlas.application.HelloBikeApp.onCreate(HelloBikeApp.java:87)
02-25 23:43:30.471 E/easybike_easybike(10313): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
02-25 23:43:30.471 E/easybike_easybike(10313): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5530)
02-25 23:43:30.471 E/easybike_easybike(10313): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
02-25 23:43:30.471 E/easybike_easybike(10313): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360)
02-25 23:43:30.471 E/easybike_easybike(10313): 	at android.app.ActivityThread.handleBindApplication(<Xposed>)
02-25 23:43:30.471 E/easybike_easybike(10313): 	at android.app.ActivityThread.-wrap2(ActivityThread.java)
02-25 23:43:30.471 E/easybike_easybike(10313): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1611)
02-25 23:43:30.471 E/easybike_easybike(10313): 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-25 23:43:30.471 E/easybike_easybike(10313): 	at android.os.Looper.loop(Looper.java:165)
02-25 23:43:30.471 E/easybike_easybike(10313): 	at android.app.ActivityThread.main(ActivityThread.java:6375)
02-25 23:43:30.471 E/easybike_easybike(10313): 	at java.lang.reflect.Method.invoke(Native Method)
02-25 23:43:30.471 E/easybike_easybike(10313): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
02-25 23:43:30.471 E/easybike_easybike(10313): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
02-25 23:43:30.471 E/easybike_easybike(10313): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)

**Comment by asLody** [comment]
WhaleRuntime在加载过程中已输出了错误信息，你需要贴出错误信息

**Comment by openproject** [comment]
是不是这个错误，换了个红米 Note 7, 好像和 xposed 没有关系：
03-03 23:48:27.959 E/Whale   (13149): Unable to read data from libart.so.
03-03 23:48:27.959 E/Whale   (13149): Runtime setup failed
03-03 23:48:27.959 D/AndroidRuntime(13149): Shutting down VM

--------- beginning of crash
03-03 23:48:27.960 E/AndroidRuntime(13149): FATAL EXCEPTION: main
03-03 23:48:27.960 E/AndroidRuntime(13149): Process: com.xxxx, PID: 13149
03-03 23:48:27.960 E/AndroidRuntime(13149): java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/com.jingyao.easybike-rb5R_nNdi7pC68eYY48M1A==/lib/arm/libwhale.so"
03-03 23:48:27.960 E/AndroidRuntime(13149): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
03-03 23:48:27.960 E/AndroidRuntime(13149): 	at java.lang.System.loadLibrary(System.java:1669)
03-03 23:48:27.960 E/AndroidRuntime(13149): 	at com.lody.whale.WhaleRuntime.<clinit>(WhaleRuntime.java:19)
03-03 23:48:27.960 E/AndroidRuntime(13149): 	at com.lody.whale.WhaleRuntime.hookMethodNative(Native Method)
03-03 23:48:27.960 E/AndroidRuntime(13149): 	at com.lody.whale.xposed.XposedBridge.hookMethod(XposedBridge.java:100)
03-03 23:48:27.960 E/AndroidRuntime(13149): 	at com.lody.whale.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:187)
03-03 23:48:27.960 E/AndroidRuntime(13149): 	at com.jingyao.easybike.tools.upi.Hooks.init(Hooks.kt:26)
03-03 23:48:27.960 E/AndroidRuntime(13149): 	at com.hellobike.atlas.application.HelloBikeApp.onCreate(HelloBikeApp.java:88)
03-03 23:48:27.960 E/AndroidRuntime(13149): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1155)
03-03 23:48:27.960 E/AndroidRuntime(13149): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5949)
03-03 23:48:27.960 E/AndroidRuntime(13149): 	at android.app.ActivityThread.access$1200(ActivityThread.java:200)
03-03 23:48:27.960 E/AndroidRuntime(13149): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1673)
03-03 23:48:27.960 E/AndroidRuntime(13149): 	at android.os.Handler.dispatchMessage(Handler.java:106)
03-03 23:48:27.960 E/AndroidRuntime(13149): 	at android.os.Looper.loop(Looper.java:201)
03-03 23:48:27.960 E/AndroidRuntime(13149): 	at android.app.ActivityThread.main(ActivityThread.java:6810)
03-03 23:48:27.960 E/AndroidRuntime(13149): 	at java.lang.reflect.Method.invoke(Native Method)
03-03 23:48:27.960 E/AndroidRuntime(13149): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
03-03 23:48:27.960 E/AndroidRuntime(13149): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by hl46000** [comment]
Same issue on J710F Android 8.1.0 armeabi-v7a. I was use Xposed(Systemless) to load libwhale.so and mylib.so to another application.
03-06 18:39:51.849 7095-7095/? D/NaviteHook: Failed to load Whale: JNI_ERR returned from JNI_OnLoad in "/data/data/com.hl46000.hlfaker/lib/libwhale.so"
03-06 18:39:51.852 7095-7095/? E/HLHooker: HLHooker Load Hook!!!
03-06 18:39:51.914 7115-7115/? A/DEBUG:     #01 pc 000374ed  /data/app/com.hl46000.hlfaker-_AkG2KdCEmMXkIoeWcAE5w==/lib/arm/libwhale.so
03-06 18:39:51.914 7115-7115/? A/DEBUG:     #02 pc 0003e257  /data/app/com.hl46000.hlfaker-_AkG2KdCEmMXkIoeWcAE5w==/lib/arm/libwhale.so
03-06 18:39:51.914 7115-7115/? A/DEBUG:     #03 pc 0003a19f  /data/app/com.hl46000.hlfaker-_AkG2KdCEmMXkIoeWcAE5w==/lib/arm/libwhale.so
03-06 18:39:51.914 7115-7115/? A/DEBUG:     #04 pc 00036c43  /data/app/com.hl46000.hlfaker-_AkG2KdCEmMXkIoeWcAE5w==/lib/arm/libwhale.so (WInlineHookFunction+126)
03-06 18:39:51.914 7115-7115/? A/DEBUG:     #05 pc 000113ff  /data/app/com.hl46000.hlfaker-_AkG2KdCEmMXkIoeWcAE5w==/lib/arm/libhlhooker.so (JNI_OnLoad+38)
