### ISSUE TITLE
跑不了

### ISSUE THREAD

**Issue by Dd-ouni** [asLody/whale#19]
`
04-12 19:15:19.055 3147-3147/? E/memtrack: Couldn't load memtrack module (No such file or directory)
04-12 19:15:19.055 3147-3147/? E/android.os.Debug: failed to load memtrack module: -2
04-12 19:15:19.261 3163-3163/? E/memtrack: Couldn't load memtrack module (No such file or directory)
04-12 19:15:19.261 3163-3163/? E/android.os.Debug: failed to load memtrack module: -2
04-12 19:15:20.352 3174-3174/? E/memtrack: Couldn't load memtrack module (No such file or directory)
04-12 19:15:20.352 3174-3174/? E/android.os.Debug: failed to load memtrack module: -2
04-12 19:15:20.387 3174-3183/? E/art: Thread attaching while runtime is shutting down: Binder_1
04-12 19:15:20.693 3187-3187/? E/memtrack: Couldn't load memtrack module (No such file or directory)
04-12 19:15:20.693 3187-3187/? E/android.os.Debug: failed to load memtrack module: -2
04-12 19:15:20.721 3187-3195/? E/art: Thread attaching while runtime is shutting down: Binder_1
04-12 19:15:21.254 3196-3196/com.example.day42 A/libc: Fatal signal 11 (SIGSEGV), code 2, fault addr 0x3173f888 in tid 3196 (m.example.day42)
04-12 19:15:21.489 1509-2871/system_process E/EGL_adreno: tid 2871: eglSurfaceAttrib(1266): error 0x3009 (EGL_BAD_MATCH)
04-12 19:15:21.690 3218-3218/com.example.day42 A/libc: Fatal signal 11 (SIGSEGV), code 2, fault addr 0x3173f888 in tid 3218 (m.example.day42)
04-12 19:15:21.898 3241-3250/? E/art: Failed writing handshake bytes (-1 of 14): Broken pipe
04-12 19:15:21.907 1509-2871/system_process E/EGL_adreno: tid 2871: eglSurfaceAttrib(1266): error 0x3009 (EGL_BAD_MATCH)
04-12 19:15:22.139 3241-3241/? A/libc: Fatal signal 11 (SIGSEGV), code 2, fault addr 0x3173f888 in tid 3241 (m.example.day42)
04-12 19:15:22.313 1337-1337/? E/lowmemorykiller: Error opening /proc/3241/oom_score_adj; errno=2
04-12 19:15:28.874 1509-1567/system_process E/WifiStateMachine: WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=0.00 rxSuccessRate=0.00 targetRoamBSSID=00:81:25:08:db:c6 RSSI=-45
04-12 19:15:48.879 1509-1567/system_process E/WifiStateMachine: WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=0.00 rxSuccessRate=0.00 targetRoamBSSID=00:81:25:08:db:c6 RSSI=-45
`

`package com.example.day42;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.widget.TextView;

import com.lody.whale.xposed.XC_MethodHook;
import com.lody.whale.xposed.XposedHelpers;
public class MainActivity extends AppCompatActivity {
    private static final String TAG = "MainActivity";
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        try {
            XposedHelpers.findAndHookMethod(
                    Test.class,
                    "myname",
                    new XC_MethodHook(){
                        @Override
                        protected void beforeHookedMethod(MethodHookParam param) throws Throwable {
                            super.beforeHookedMethod(param);

                        }

                        @Override
                        protected void afterHookedMethod(MethodHookParam param) throws Throwable {
                            super.afterHookedMethod(param);

                            param.setResult("你大爷的大西瓜");
                        }
                    });
        }catch (Exception e){

            e.printStackTrace();
        }

        TextView textView = (TextView) findViewById(R.id.main_text);
        Test test = new Test();
        textView.setText(test.myname());

    }
}`

环境：雷电模拟器 5.1.1

**Comment by asLody** [comment]
暂不支持libhoudini.so Runtime.
