### ISSUE TITLE
运行时崩溃

### ISSUE THREAD

**Issue by kakayang2011** [asLody/whale#20]
Fatal signal 11 (SIGSEGV), code 1, fault addr 0xe3 in tid 2513 (pool-19-thread-)
Build fingerprint: 'SMARTISAN/oxford/oxford:7.1.1/NGI77B/1526981672:user/dev-keys'
Revision: '0'
ABI: 'arm'
pid: 2284, tid: 2513, name: pool-19-thread- >>> com.mm.android.mika<<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xe3
r0 000000d3 r1 e5be5140 r2 0001000a r3 c1a6b067
r4 0000002d r5 e5b83000 r6 000000c7 r7 d656f000
r8 c1a6b05c r9 c1a6b067 sl 00000000 fp 00000000
ip 7093eaaa sp c1a6b000 lr e571631f pc e5750740 cpsr 200d0030
backtrace:
#00 pc 000ec740 /system/lib/libart.so (_ZN3art11ClassLinker16FindOatMethodForEPNS_9ArtMethodEPb+319)
#01 pc 000b231b /system/lib/libart.so (_ZN3art9ArtMethod23GetOatQuickMethodHeaderEj+158)
#02 pc 00353aa7 /system/lib/libart.so (_ZN3art12StackVisitor9WalkStackEb+106)
#03 pc 00357a01 /system/lib/libart.so (_ZNK3art6Thread24CreateInternalStackTraceILb0EEEP8_jobjectRKNS_33ScopedObjectAccessAlreadyRunnableE+56)
#04 pc 002d1471 /system/lib/libart.so (_ZN3artL32Throwable_nativeFillInStackTraceEP7_JNIEnvP7_jclass+28)
#05 pc 00527a55 /system/framework/arm/boot.oat (offset 0x51b000) (java.lang.Throwable.nativeFillInStackTrace+72)
#06 pc 005288ef /system/framework/arm/boot.oat (offset 0x51b000) (java.lang.Throwable.fillInStackTrace+74)
#07 pc 005275e7 /system/framework/arm/boot.oat (offset 0x51b000) (java.lang.Throwable.<init>+138)
#08 pc 00529289 /system/framework/arm/boot.oat (offset 0x51b000) (java.lang.Exception.<init>+44)
#10 pc 005a76f9 /system/framework/arm/boot.oat (offset 0x51b000) (java.lang.UnsupportedOperationException.<init>+44)
#09 pc 0055a119 /system/framework/arm/boot.oat (offset 0x51b000) (java.lang.RuntimeException.<init>+44)
#11 pc 000aa241 /system/lib/libart.so (art_quick_invoke_stub_internal+64)
#12 pc 004323b3 /system/lib/libart.so (art_quick_invoke_stub+230)
#13 pc 000b1a79 /system/lib/libart.so (_ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc+144)
#14 pc 00207e81 /system/lib/libart.so (_ZN3art11interpreter34ArtInterpreterToCompiledCodeBridgeEPNS_6ThreadEPNS_9ArtMethodEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+200)
#15 pc 00201fe1 /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+432)
#16 pc 0042accf /system/lib/libart.so (MterpInvokeDirect+270)
#17 pc 0009d194 /system/lib/libart.so (ExecuteMterpImpl+14484)
#18 pc 001e51c7 /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+282)
#19 pc 001e9c7f /system/lib/libart.so (_ZN3art11interpreter33ArtInterpreterToInterpreterBridgeEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+114)
#20 pc 00201fc9 /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+408)
#21 pc 0042c7cd /system/lib/libart.so (MterpInvokeVirtualQuick+316)
#22 pc 000a0e14 /system/lib/libart.so (ExecuteMterpImpl+29972)
#23 pc 001e51c7 /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+282)
#24 pc 001e9c7f /system/lib/libart.so (_ZN3art11interpreter33ArtInterpreterToInterpreterBridgeEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+114)
#25 pc 00201fc9 /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+408)
#26 pc 0042c7cd /system/lib/libart.so (MterpInvokeVirtualQuick+316)
#27 pc 000a0e14 /system/lib/libart.so (ExecuteMterpImpl+29972)
#28 pc 001e51c7 /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+282)
#29 pc 001e9c7f /system/lib/libart.so (_ZN3art11interpreter33ArtInterpreterToInterpreterBridgeEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+114)
#30 pc 00201fc9 /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+408)

**Comment by asLody** [comment]
Fixed.
