### ISSUE TITLE
hook 不到 android.app.ActivityThread 的 systemMain 方法

### ISSUE THREAD

**Issue by bmax121** [asLody/whale#7]
arm64, android 7.1.2 , lineageos14

**Comment by WindySha** [comment]
systemMain()只在system_server进程启动时才会调用，你自己的进程启动更本不会调用到，因此无法hook到

**Comment by WindySha** [comment]
SystemServer.java

```
private void createSystemContext() {
        ActivityThread activityThread = ActivityThread.systemMain();
        mSystemContext = activityThread.getSystemContext();
        mSystemContext.setTheme(DEFAULT_SYSTEM_THEME);

        final Context systemUiContext = activityThread.getSystemUiContext();
        systemUiContext.setTheme(DEFAULT_SYSTEM_THEME);
    }
```

**Comment by bmax121** [comment]
在 zygote 进程中 hook 的，类似 xposed

**Comment by bmax121** [comment]
} else if (startsSystemServer) {
            Log.d("xxxx", "startsSystemServer");

            findAndHookMethod(ActivityThread.class, "systemMain", new DC_MethodHook() {
                @Override
                protected void afterHookedMethod(MethodHookParam param) throws Throwable {
                    final ClassLoader cl = Thread.currentThread().getContextClassLoader();

                    Log.d("xxxxxx", "systemMain");
